### ISSUE TITLE
Buttons for Power On/Off

### ISSUE THREAD

**Issue by chromie123** [misorrek/ViscaCamLink#6]
Firstly, many thanks for this very practical programme. Is it possible to add two more small buttons? Unfortunately, we still have to use the remote control for the camera's stand-by mode.

**Power ON:**  8x 01 04 00 02 FF
**Power OFF:**  8x 01 04 00 03 FF

**Comment by misorrek** [comment]
Hei, thank you for your feedback, good suggestion! I'll try to look into it in the near future ^^

**Comment by chromie123** [comment]
Thank you very much for your effort! We are looking forward to it :)

Am Mi., 20. Dez. 2023 um 21:30 Uhr schrieb Max ***@***.***>:

**Comment by misorrek** [comment]
Hei again, i finally managed it to publish a new version which includes a button to turn the camera on and off. You can find this in the "Pre-Release 4". I would like to here your feedback on this. Until then, have a good time!

**Comment by chromie123** [comment]
Many thanks for the good work. The update worked well, the camera was found immediately and switching it on and off has always worked so far.
