### ISSUE TITLE
Language Translations

### ISSUE THREAD

**Issue by webnerdnick** [misorrek/ViscaCamLink#7]
Thank you for this work. Any chance for translations? Perhaps different configuration files for each language, and then add a setting in configuration file that switches the language? I'd be happy to help make translations.

**Comment by misorrek** [comment]
Hei, thank you too! Translations are actually something I have wanted to do for a while. In the time I've got, I have been working on some other things, but I will look into it next. Thank you also for offering your help. I'll write to you when I’m on it. ^^

**Comment by misorrek** [comment]
Hei, lately I got some time to work on localization for this app and I put out a new version. In there I made some basic translations into english. If you want to take a look at it, you'll find the localization file here "[ViscaCamLink/Resources/Strings.resx](https://github.com/misorrek/ViscaCamLink/blob/0.3.0-pre/ViscaCamLink/Resources/Strings.resx)" in the "0.3.0-pre" branch.
